### ISSUE TITLE
Phoenix issue-Distribution-IBM BigInsights- Hbase(1.1.1)-Phoenix 4.7

### ISSUE THREAD

**Issue by anupriya231** [forcedotcom/phoenix#745]
When I try to create a table with any columns having data type other than varchar(I tried double and unsigned double) throws below error.
Error: ERROR 201 (22000): Illegal data. Expected length of at least 8 bytes, but had 4 (state=22000,code=201)
java.sql.SQLException: ERROR 201 (22000): Illegal data. Expected length of at least 8 bytes, but had 4
        at org.apache.phoenix.exception.SQLExceptionCode$Factory$1.newException(SQLExceptionCode.java:422)
        at org.apache.phoenix.exception.SQLExceptionInfo.buildException(SQLExceptionInfo.java:145)
        at org.apache.phoenix.schema.KeyValueSchema.next(KeyValueSchema.java:211)
        at org.apache.phoenix.expression.ProjectedColumnExpression.evaluate(ProjectedColumnExpression.java:115)
        at org.apache.phoenix.compile.ExpressionProjector.getValue(ExpressionProjector.java:69)
        at org.apache.phoenix.jdbc.PhoenixResultSet.getObject(PhoenixResultSet.java:524)
        at sqlline.Rows$Row.<init>(Rows.java:157)
        at sqlline.BufferedRows.<init>(BufferedRows.java:38)
        at sqlline.SqlLine.print(SqlLine.java:1650)
        at sqlline.Commands.execute(Commands.java:833)
        at sqlline.Commands.sql(Commands.java:732)
        at sqlline.SqlLine.dispatch(SqlLine.java:808)
        at sqlline.SqlLine.begin(SqlLine.java:681)
        at sqlline.SqlLine.start(SqlLine.java:398)
        at sqlline.SqlLine.main(SqlLine.java:292)

Works fine if I use varchar as datatype  for every column. Please help me with this issue?

Thanks,
Anupriya

**Comment by jtaylor-sfdc** [comment]
Please post questions on our Apache mailing list. This Google group is
defunct.

On Aug 2, 2016, at 8:21 AM, anupriya231 <notifications@github.com> wrote:

When I try to create a table with any columns having data type other than
varchar(I tried double and unsigned double) throws below error.
Error: ERROR 201 (22000): Illegal data. Expected length of at least 8
bytes, but had 4 (state=22000,code=201)
java.sql.SQLException: ERROR 201 (22000): Illegal data. Expected length of
at least 8 bytes, but had 4
at
org.apache.phoenix.exception.SQLExceptionCode$Factory$1.newException(SQLExceptionCode.java:422)
at
org.apache.phoenix.exception.SQLExceptionInfo.buildException(SQLExceptionInfo.java:145)
at org.apache.phoenix.schema.KeyValueSchema.next(KeyValueSchema.java:211)
at
org.apache.phoenix.expression.ProjectedColumnExpression.evaluate(ProjectedColumnExpression.java:115)
at
org.apache.phoenix.compile.ExpressionProjector.getValue(ExpressionProjector.java:69)
at
org.apache.phoenix.jdbc.PhoenixResultSet.getObject(PhoenixResultSet.java:524)
at sqlline.Rows$Row.(Rows.java:157)
at sqlline.BufferedRows.(BufferedRows.java:38)
at sqlline.SqlLine.print(SqlLine.java:1650)
at sqlline.Commands.execute(Commands.java:833)
at sqlline.Commands.sql(Commands.java:732)
at sqlline.SqlLine.dispatch(SqlLine.java:808)
at sqlline.SqlLine.begin(SqlLine.java:681)
at sqlline.SqlLine.start(SqlLine.java:398)
at sqlline.SqlLine.main(SqlLine.java:292)

Works fine if I use varchar as datatype for every column. Please help me
with this issue?

Thanks,
Anupriya

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/forcedotcom/phoenix/issues/745>, or mute the thread
